apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo
spec:
  type: NodePort
  selector:
    app: spring-boot-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
